### PR TITLE
First batch of merges

### PR DESCRIPTION
**Pull request by sjjs7**
The first 33 commits merged with no conflict. Along with those commits, the 6 that were previously skipped also got merged in. Also ignore commits ab02208 and d458a41, I was experimenting- sorry about that, hopefully you can choose not to merge those.

### CODE REVIEW

**Comment by sjjs7** [comment]
I also didn't fix the merge conflict the first time in 30c70f3 but corrected myself in the following commits. Hopefully now I can fix  conflict in just 1 commit!

I also changed holtest and the Makefile in Mizar because they were causing bugs.

**Review by JacquesCarette — APPROVED** [review]
This seems like a successful merge that shouldn't break anything.

**Comment by JacquesCarette** [comment]
I'll wait until you give me the final green light to merge, but as far as I can tell, this looks good.

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
I approved the extra change, not necessarily the whole thing. `holtest` is still broken, right?

**Comment by sjjs7** [comment]
Yes correct. As soon as I get Ocaml up and running on this other server I
will run plain hol light's holtest to use as a comparison against running
plain hol QE's holtest.

I understand I'm comparing the time it takes to run files they have in
common? I believe time is already being measured in the holtest file so all
I need to do is run and save output.

**Comment by sjjs7** [comment]
That one merge was me trying to merge to a branch other than master. I got it now!

**Comment by JacquesCarette** [comment]
Yes, you want to compare the ones that are in common.  Good that it already measures time.

Hopefully, the increased access that Derek gave you will help. I'm surprised it's this hard!  Normally, `opam`, especially on linuxes, is easy to install.

**Comment by sjjs7** [comment]
Yeah, I'm not sure what I was doing wrong- I couldn't get the bubblewrap to install. So this time I'll try downloading opam the not-from-scratch way.

**Comment by JacquesCarette** [comment]
It still depends on `blwrap`, AFAIK, so that will need to be installed somehow. Hopefully the package manager(s) can deal with it gracefully.

**Comment by sjjs7** [comment]
I pushed a bunch more merge commits to master by mistake! 
It wasn't a lot, I'll make sure to be more careful.

**Comment by sjjs7** [comment]
Just going to triple check these work fine, I will let you know ASAP.

**Comment by JacquesCarette** [comment]
Thanks.

**Comment by sjjs7** [comment]
Alright, looks good to go.

**Comment by JacquesCarette** [comment]
Great - done!

**Comment by JacquesCarette** [comment]
Note that you should, in general, do further merges into a different branch than 'master' on your fork.

**Pull request merged**
