### PR TITLE
second batch

### PR DESCRIPTION
**Pull request by sjjs7**
Will let you know when these are good to go.

### CODE REVIEW

**Comment by sjjs7** [comment]
These are good to go, whenever you're ready.

**Review by JacquesCarette — APPROVED** [review]
Weirdly, the first 1/3 of the changes all seem to be "no actual changes" -- maybe line-ending only?

**Comment by sjjs7** [comment]
Could it be because the first 'commit' was just the pull request I did by merging the second batch branch into my main branch?

**Comment by sjjs7** [comment]
Oh nvm I see what you mean...that is strange

**Comment by sjjs7** [comment]
You're right, looks like it is from me changing the line endings (commit 
b20cba9). Will that affect the way QE is run for 'everyone'?

**Comment by JacquesCarette** [comment]
It shouldn't affect QE, I think. Just the diffs. Unless some platform is weird, and gets confused because of line endings.  Let's not worry about it, as we now know what the reason is.

**Pull request merged**
