### PR TITLE
fourth batch

### PR DESCRIPTION
**Pull request by sjjs7**

### CODE REVIEW

**Comment by sjjs7** [comment]
These are also good to go if the conflicts again don't require me to change anything.

**Comment by JacquesCarette** [comment]
Conflicts again. In part because you're still working directly on master, so it makes the patch be "from the start" (128 commits!!!) instead of the just the latest batch.  Can you try to fix this?

**Comment by sjjs7** [comment]
Yes, I see.

**Comment by sjjs7** [comment]
Actually that is the latest batch. I made this one bigger because it had a lot of PR's in them which appear as 2 commits but they really only make 1 change. 
Also every time I do a merge commit it shows as a commit (as you can see) which is quite annoying, but also makes the number of commits looks larger than they are.

That being said, can I go ahead and fix these conflicts?

**Comment by JacquesCarette** [comment]
Yes, go ahead.

**Comment by sjjs7** [comment]
Good to merge.

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
